Style/NumericPredicate:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Layout/EmptyLinesAroundArguments:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Max: 30
