Style/NumericPredicate:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Layout/EmptyLinesAroundArguments:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 40
Metrics/BlockLength:
  Max: 40
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
